//########################################
//# This page contains score data, timing data and the media file path. Save it as a text file in
//# the same folder as abcweb.html. Abcweb preloads score and media when it is opened with the
//# file name as parameter in the url, for example: http://your.domain.org/abcweb.html?file_name
//# Also works locally with file:///path/to/abcweb.html?file_name
//# **** You have to correct the path to the media file below! (media_file="...";) ****
//########################################
//#
media_file = "Bach Orchestral Suite 2 In B Minor BWV 1067 - 7. Badinerie.mp3";
offset_js = 0.00;
opt = {"jump":0,"no_menu":0,"repufld":0,"noplyr":0,"nocsr":0,"media_height":"","btns":1,"ipadr":"","mstr":0,"autscl":0,"ctrmed":0,"ctrnot":0,"lncsr":true,"opacity":0.2,"synbox":0,"speed":1,"top_margin":0,"yubvid":"","nomed":0,"delay":0,"repskip":0,"spdctl":true,"lopctl":false,"metro":0,"btime":-1,"etime":0};
lpRec = {"loopBtn":1,"loopStart":0,"loopEnd":82.2909090909091};
times_arr = [[0.00,0.93,1.92,2.99,4.06,5.27,6.31,7.48,8.64,9.61],
[9.61,10.59,11.67,12.75,13.84,14.94,16.03,17.13,18.03,18.03,19.42],
[19.42,20.31,21.21,22.40,23.70,24.79,25.89,26.98,28.08,29.17,30.27],
[30.27,31.36,32.46,33.55,34.45,34.74,35.94,37.13,38.23,39.32,40.52],
[40.52,41.72,42.81,43.81,44.80,45.80,47.09,48.09,49.28,50.28,51.47],
[51.47,52.47,53.66,54.66,56.05,57.05,58.04,59.04,60.23,61.23,62.32],
[62.32,62.82,63.92,65.01,66.11,67.20,68.30,69.39,70.49,71.58,72.68],
[72.68,73.77,74.87,75.96,77.06,78.15,79.25,80.34,81.44,82.53,83.63],
[83.63,84.72,85.82,86.91,88.01,89.11]];
abc_arr = ["X:1",
"T:Badinerie",
"C:J.S.Bach",
"%%scale 0.62",
"%%score [ 1 { 2 3 } 4 5 6 ] { 7 | 8 }",
"L:1/8",
"M:2/4",
"I:linebreak $",
"K:D",
"V:1 treble nm=\"Flauto Traverso\" snm=\"Fl.\"",
"L:1/16",
"V:2 treble nm=\"Violins\" snm=\"Vlns.\"",
"V:3 treble nm=\"Violins\" snm=\"Vlns.\"",
"V:4 alto nm=\"Violas\" snm=\"Vlas.\"",
"V:5 bass nm=\"Violoncellos\" snm=\"Vcs.\"",
"V:6 bass transpose=-12 nm=\"Contrabasses\" snm=\"Cbs.\"",
"V:7 treble nm=\"Harpsichord\" snm=\"Hch.\"",
"L:1/16",
"V:8 bass ",
"V:1",
"!f!!fff! .b2.d'.b | .f2.b.f .d2.f.d | B4 FBdB | cBcB ^Acec | d2B2 .b2.d'.b | .f2.b.f .d2.f.d | %6",
" B4 d2d2 | d2d2 b2d2 |$ Td2c2 f2f2 | f2f2 d'2f2 | Tf2^e2 cfaf | ^gfgf ^egbg | a^gag fa(f^e | %13",
" f)b(f^e f)c'(fe |$ f)d'(f^e f)d'c'b | c'a^gf a2Tg2 | f4 :: .f2.a.f | .c2.f.c .A2.c.A | F4 =c2B2 | %20",
" e2^df a2gf | g2e2 g2bg | e2ge c2ec |$ A4- Adfd | eded cege | fefe dfdc | dgdc dadc | dbdc dbag | %28",
" afed f2Te2 | d4 .f2.f2 | .f2.f2 .d'2.f2 |$ Tf2.e2 .e2.e2 | .e2.e2 .c'2.e2 | Te2d2 b2d'b | %34",
"{a} g4- g2(b/a/g/f/) | e4- e2(g/f/e/d/) | =cege cBcB | (^A2F2) (G2F2) |$ (B2^A)c e2dc | %39",
" d2(B/c/d/e/ f2)df |[Q:1/4=110] .b2.f2[Q:1/4=100] edcd |[Q:1/4=40] B4 :| %42",
"V:2",
"!f! .b z | .f z .d z | B2 .B.d | .c.c .c.e | .d.B .b z | .f z .d z | B2 d/c/d- | d/c/d- d/b/d |$ %8",
" Tdc f/^e/f- | f/^e/f- f/d'/f | Tf^e .f.a | .^g.g .g.b | af/^e/ .f.c | .f.B .f.A |$ .f.^G .f.^e | %15",
" .f.^g .c.^e | f2 :: .f z | .c z .A z | F2!p! .A z | .G z .F z | .E z!f! .g z | .g z .e z |$ %23",
" c2 .d.f | .e.e .e.g | .f.d/.c/ .d.A | .d.G .d.F | .d.E .d.c | .d.e .A.c | d2 f/e/f- | %30",
" f/e/f- f/d'/f |$ Tfe e/d/e | e/d/e e/c'/e | Ted z2 | z g/e/ .B z | z e/B/ .G z | z .=c .e.g | %37",
"{g} f2!p! .e z |$ .d z .c z | B!f!F/B/ d/B/d/f/ | .b.f e/d/c/d/ | B2 :| %42",
"V:3",
"!f! .f z | .d z .B z | F2 .F.B | .B.B .^A.A | .B.F .f z | .d z .B z | F2 .F.B | .E.B .^G.B |$ %8",
" .A.E .A.d | .^G.d .B.d | .c.^G .c.f | .f.f .^e.e | .f.A .c z | .B z .A z |$ .^G z .B.d | %15",
" .c.B .A.c | c2 :: .c z | .A z .F z | C2!p! .F z | .E z .^D z | .E z!f! .e z | .e z .c z |$ %23",
" A2 .A.d | .d.d .c.c | .d.F .A z | .G z .F z | .E z .B.e | .A.G .F.A | A2 .A.d | .A.d .A.d |$ %31",
" Tdc .F.c | .F.c .^A.c | TcB z2 | z e/B/ .G z | z B/G/ .E z | z .E .G.=c |{B} ^A2!p! .c z |$ %38",
" .B z .^A z | B2 z!f! B/d/ | .f.B .B.^A | F2 :| %42",
"V:4",
"!f! .d z | .B z .F z | D2 .D.F | .G.E .F.F | .F.D .d z | .B z .F z | D2 .B.F | .B.^G .B.E |$ %8",
" .E.A .F.A | .d.B .d.^G | .^G.c .F.c | .d.d .c.c | .C.c .A z | .F z .A z |$ .B z .^G.B | %15",
" .A.d .c.B | A2 :: .A z | .F z .C z | A,2!p! .F, z | .G, z .B, z | .B, z!f! .B z | .A z .A z |$ %23",
" E2 .A.F | .B.G .A.A | .A,.A .F z | .D z .F z | .G z .E.G | .F.B .A.G | F2 .d.A | .D.A .F.A |$ %31",
" A2 .c.^A | .c.^A .c.F | F2 z2 | z B/G/ .E z | z G/E/ .B, z | z .G, .=C.E | C2!p! .C z |$ %38",
" .D z .F z | F2 z!f! F/B/ | .d.D .C.F | D2 :| %42",
"V:5",
"!f! .B,,.B,, | .D,.B,, .F,.D, | .B,.F, .D,.B,, | .E,.C, .F,.F,, | B,,/C,/D,/C,/ .B,,.B,, | %5",
" .D,.B,, .F,.D, | .B,.F, B,D/B,/ | ^G,B,/G,/ E,G,/E,/ |$ A,C/A,/ DF/D/ | B,D/B,/ ^G,B,/G,/ | %10",
" C/D/C/B,/ .A,.F, | .B,.^G, .C.C, | .F,.F,, .F,.A, | .B,,.B, .C,.C |$ .B,,.D .B,.^G, | %15",
" .A,.B, .C.C, | F,2 :: .F,,.F,, | .A,,.F,, .C,.A,, | F,A,/F,/!p! ^D,F,/D,/ | (B,,B,, B,,B,,) | %21",
" E,B,/G,/!f! E,G,/E,/ | .C,.A,, .E,.C, |$ .G,.E, .F,.B, | .G,.E, .A,.A,, | .D,.D,, .=C,.F, | %26",
" .B,,.G, .A,,.A, | .G,,.B, .G,.E, | .F,.G, .A,.A,, | D,A,,/F,,/ D,,D/A,/ | F,A,/F,/ D,F,/D,/ |$ %31",
" A,E,/C,/ ^A,,E/C/ | ^A,C/A,/ F,A,/F,/ | B,F, D,B,, | (E,E, E,)E,, | (E,E, E,)E,, | (E,E, E,)E,, | %37",
" .E,E/C/!p! .^A,C/A,/ |$ .F,.F, .F,.F, | .B,D/B,/!f! .F,B,/F,/ | D,B,,/D,/ F,F,, | B,,2 :| %42",
"V:6",
"!f! .B,,.B,, | .D,.B,, .F,.D, | .B,.F, .D,.B,, | .E,.C, .F,.F,, | B,,/C,/D,/C,/ .B,,.B,, | %5",
" .D,.B,, .F,.D, | .B,.F, B,D/B,/ | ^G,B,/G,/ E,G,/E,/ |$ A,C/A,/ DF/D/ | B,D/B,/ ^G,B,/G,/ | %10",
" C/D/C/B,/ .A,.F, | .B,.^G, .C.C, | .F,.F,, .F,.A, | .B,,.B, .C,.C |$ .B,,.D .B,.^G, | %15",
" .A,.B, .C.C, | F,2 :: .F,,.F,, | .A,,.F,, .C,.A,, | F,A,/F,/!p! ^D,F,/D,/ | (B,,B,, B,,B,,) | %21",
" E,B,/G,/!f! E,G,/E,/ | .C,.A,, .E,.C, |$ .G,.E, .F,.B, | .G,.E, .A,.A,, | .D,.D,, .=C,.F, | %26",
" .B,,.G, .A,,.A, | .G,,.B, .G,.E, | .F,.G, .A,.A,, | D,A,,/F,,/ D,,D/A,/ | F,A,/F,/ D,F,/D,/ |$ %31",
" A,E,/C,/ ^A,,E/C/ | ^A,C/A,/ F,A,/F,/ | B,F, D,B,, | (E,E, E,)E,, | (E,E, E,)E,, | (E,E, E,)E,, | %37",
" .E,E/C/!p! .^A,C/A,/ |$ .F,.F, .F,.F, | .B,D/B,/!f! .F,B,/F,/ | D,B,,/D,/ F,F,, | B,,2 :| %42",
"V:7",
"!f!!f!!f! .[Bdfb]2 z2 | .[Bdf]2 z2 .[FBd]2 z2 | .[DFB]2 z2 DFBF | GFED EFcF | dcB^A .[Bdfb]2 z2 | %5",
" .[Bdf]2 z2 .[FBd]2 z2 | .[DFB]2 z2 dcd2 | B2dB ^G2BG |$ ABcB A2dc | d2fd B2dB | ABcB Acfc | %11",
" dcBA B^GcB | A^GF^E FAcE | FBd^E FAcE |$ FBd^E FBdB | AcfA ^GfG^e | [Acf]4 :: [Acf]2 z2 | %18",
" [FAc]2 z2 [CFA]2 z2 | [A,CF]4!p! ^DFBF | ^DFB^d gfed | e2 z2!f! [Beg]2 z2 | [Aeg]2 z2 [Ace]2 z2 |$ %23",
" [EAc]4 FAdA | BAGF GAeA | fedc dAdc | dBdc d=cd^c | dGdc dGfe | FAdF EdEc | [FAd]4 Adfd | %30",
" Adfd Adfd |$ gfed Fcec | Fcec Fcec | fedc B2 z2 | geBe g2 z2 | eBGB e2 z2 | G=cec cBcB | %37",
" ^A2cA!p! F2AF |$ D2CE ^A2^GA | BF[I:staff +1]D[I:staff -1]F!f! BFBd | f2 DB CBC^A | [DFB]4 :| %42",
"V:8",
"!f! .B,,.B,, | .D,.B,, .F,.D, | .B,.F, .D,.B,, | .E,.C, .F,.F,, | B,,/C,/D,/C,/ .B,,.B,, | %5",
" .D,.B,, .F,.D, | .B,.F, B,D/B,/ | ^G,B,/G,/ E,G,/E,/ |$ A,C/A,/ DF/D/ | B,D/B,/ ^G,B,/G,/ | %10",
" C/D/C/B,/ .A,.F, | .B,.^G, .C.C, | .F,.F,, .F,.A, | .B,,.B, .C,.C |$ .B,,.D .B,.^G, | %15",
" .A,.B, .C.C, | F,2 :: .F,,.F,, | .A,,.F,, .C,.A,, | F,A,/F,/ ^D,F,/D,/ | (B,,B,, B,,B,,) | %21",
" E,B,/G,/ E,G,/E,/ | .C,.A,, .E,.C, |$ .G,.E, .F,.B, | .G,.E, .A,.A,, | .D,.D,, .=C,.F, | %26",
" .B,,.G, .A,,.A, | .G,,.B, .G,.E, | .F,.G, .A,.A,, | D,A,,/F,,/ D,,D/A,/ | F,A,/F,/ D,F,/D,/ |$ %31",
" A,E,/C,/ ^A,,E/C/ | ^A,C/A,/ F,A,/F,/ | B,F, D,B,, | (E,E, E,)E,, | (E,E, E,)E,, | (E,E, E,)E,, | %37",
" .E,E/C/ .^A,C/A,/ |$ .F,.F, .F,.F, | .B,D/B,/ .F,B,/F,/ | D,B,,/D,/ F,F,, | B,,2 :| %42",
""];
abc_enc = [];
